version: 0.2

phases:
  install:
    commands:
      - echo "No installation needed for static HTML"

  pre_build:
    commands:
      - echo "Preparing build..."

  build:
    commands:
      - echo "Building static HTML site"
      - mkdir -p output
      # Copy all files to output directory
      - cp -r * output/ || true
      # Remove buildspec from artifacts
      - rm -f output/buildspec.yml

 post_build:
  commands:
    - echo "=== DEBUG: Checking AWS identity and CLI ==="
    - aws sts get-caller-identity
    - aws --version
    - echo "=== DEBUG: Checking CloudFront distribution ==="
    - aws cloudfront list-distributions --query "DistributionList.Items[*].Id"
    - echo "=== Invalidating CloudFront cache ==="
    - aws cloudfront create-invalidation --distribution-id E2V4Z0MVMLHQ5A --paths "/*" --region us-east-1

  
      
artifacts:
  files:
    - '**/*'
  base-directory: output
  discard-paths: no
